exports.up = async knex => {
	await knex("assinante").insert({
		id: 1,
		cnpj: "96.771.010/0001-08",
		descricao: "Super Mercado Casa Magalhães",
	});
	await knex("unidade").insert([
		{ id: 1, assinanteId: 1, codigo: "CX", descricao: "Caixa" },
		{ id: 83, assinanteId: 1, codigo: "FD", descricao: "Fardo" },
		{ id: 84, assinanteId: 1, codigo: "GRS", descricao: "Grosa" },
		{ id: 85, assinanteId: 1, codigo: "KG", descricao: "Quilo" },
		{ id: 86, assinanteId: 1, codigo: "L", descricao: "Litro" },
		{ id: 87, assinanteId: 1, codigo: "LT", descricao: "Lata" },
		{ id: 88, assinanteId: 1, codigo: "MIL", descricao: "Milimetros" },
		{ id: 89, assinanteId: 1, codigo: "PCT", descricao: "Pacotes" },
		{ id: 90, assinanteId: 1, codigo: "SC", descricao: "Saca" },
		{ id: 91, assinanteId: 1, codigo: "UN", descricao: "Unidade" },
	]);
	return await knex("produto").insert([
    { assinanteId:1, produtoId: 	2559	, descricao: "	UVA RUBI	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2156	, descricao: "	POLPA MARACUJA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2164	, descricao: "	REQUEIJAO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2765	, descricao: "	RONDELLI BERINJELA,RICOTA TEMPERADA,ALCAPARRA 500G	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2290	, descricao: "	CHA HORTELA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2333	, descricao: "	DETERGENTE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2334	, descricao: "	DETERGENTE CLORADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2383	, descricao: "	GOIABADA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	210	, descricao: "	SALADA PERSONALIZADA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2105	, descricao: "	MASSA WRAP LARANJA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2106	, descricao: "	MASSA WRAP NATURAL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2135	, descricao: "	PALITO INTEGRAL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2165	, descricao: "	RICOTA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2538	, descricao: "	SUCO UVA 1L	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2181	, descricao: "	ABACATE AVOCADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2549	, descricao: "	TOMATE CEREJA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2550	, descricao: "	TOMATE ITALIANO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2551	, descricao: "	TOMILHO FRESCO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2563	, descricao: "	VINAGRE BALSAMICO COZINHA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2564	, descricao: "	VINAGRE DE ALCOOL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2565	, descricao: "	VINAGRE DE ARROZ	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2566	, descricao: "	VINAGRE DE MACA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2567	, descricao: "	VINAGRE DE VINHO BRANCO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2568	, descricao: "	VINAGRE DE VINHO TINTO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2577	, descricao: "	BATATA BABY	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2600	, descricao: "	PIMENTA EM GRAOS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2704	, descricao: "	TARTELETE ESPINAFRE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	245	, descricao: "	DIVINE 70 CACAU	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2666	, descricao: "	FELSEN PREMIUM LARGER	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2587	, descricao: "	GELEIA CEBOLA CARAMELIZADA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2014	, descricao: "	AVEIA EM FLOCOS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	227	, descricao: "	BUFFET SALADAS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2766	, descricao: "	SUCO CONCENTRADO UVA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2316	, descricao: "	CONCHA RICOTA NOZES	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2394	, descricao: "	LARANJA PERA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	218	, descricao: "	BOLINHO SEM LACTOSE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	190	, descricao: "	CERVEJA DIEFEN BELGA APIMENTADA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	205	, descricao: "	BUFFET VOUCHER	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2395	, descricao: "	LARANJA UMBIGO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	189	, descricao: "	CERVEJA DIEFEN APA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	171	, descricao: "	BARRA CAKE BITES	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	206	, descricao: "	BUFFET LIVRE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2154	, descricao: "	POLPA ACEROLA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	167	, descricao: "	COMBO 5	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2107	, descricao: "	MASSA WRAP VERDE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2136	, descricao: "	PAO BAGUETE MULTIGRAOS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2155	, descricao: "	POLPA FRUTAS VERMELHAS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2166	, descricao: "	RUCULA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2539	, descricao: "	TALHARIM CHIA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2540	, descricao: "	TALHARIM COM PIMENTA CALABRESA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2558	, descricao: "	UVA ITALIA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2560	, descricao: "	VAGEM	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2581	, descricao: "	COUVE MANTEIGA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2597	, descricao: "	ERVILHA SECA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2706	, descricao: "	BARRA CHOC MEIO AMARGO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	46	, descricao: "	ENERGIZANTE 500 ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	44	, descricao: "	MAMONANA 500 ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2767	, descricao: "	SABAO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	208	, descricao: "	SALADA BABY	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2318	, descricao: "	COPO CRISTAL 500	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2398	, descricao: "	LEITE DE COCO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	191	, descricao: "	CERVEJA DIEFEN DOUBLE RED ALE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	168	, descricao: "	CAFE EXPRESSO CHOCOLATE - CANCELADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2140	, descricao: "	PAO QUEIJO CONGELADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2403	, descricao: "	LIMAO SICILIANO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	172	, descricao: "	BARRA HARTS VEGANA                              	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2139	, descricao: "	PAO HAMBURGUER GRAOS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	4	, descricao: "	ACAI - 500ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2182	, descricao: "	ABOBRINHA ITALIANA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2118	, descricao: "	MOLHO CAESAR	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2183	, descricao: "	ACAFRAO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2200	, descricao: "	AIPO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2202	, descricao: "	ALCOOL GEL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2667	, descricao: "	FELSEN HELLES	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2582	, descricao: "	FM110 REDONDA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2594	, descricao: "	ANIS ESTRELADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2648	, descricao: "	ABOBORA DOCE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2668	, descricao: "	FELSEN WITBIER	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2756	, descricao: "	CACHACA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2744	, descricao: "	MANGA IQF	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2234	, descricao: "	BANANA PRATA - CANCELADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2762	, descricao: "	RAVIOLI QUEIJO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2319	, descricao: "	COPO DESCARTAVEL 50ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	70	, descricao: "	RADIANTE 300 ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	67	, descricao: "	DE BOA 300 ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2691	, descricao: "	TOMILHO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	17	, descricao: "	AGUA SEM GAS 510ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2768	, descricao: "	BICABORNATO DE SODIO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2396	, descricao: "	LEITE CONDENSADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2397	, descricao: "	LEITE CONDENSADO ZERO LACTOZE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	66	, descricao: "	SARADO PLUS 300 ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2414	, descricao: "	MANJERONA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2424	, descricao: "	MELAO ORANGE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2456	, descricao: "	PAO BAGUETE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	55	, descricao: "	ACELERADO 300 ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	58	, descricao: "	VERDE DETOX 500 ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	247	, descricao: "	BALA FUNCIONAL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2120	, descricao: "	MOLHO TERYAKI	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2121	, descricao: "	MOLHO FRENCH ROSE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2448	, descricao: "	PALITO INTEGRAL LINHACA DOURADA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2145	, descricao: "	PASTEL ESPINAFRE RICOTA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2192	, descricao: "	AGRIAO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2197	, descricao: "	AGUA SANITARIA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2669	, descricao: "	FELSEN IPA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2595	, descricao: "	CALDO DE CARNE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2596	, descricao: "	CANELA EM CASCA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2603	, descricao: "	TAHINE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2613	, descricao: "	PASTEL PALMITO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2769	, descricao: "	SACO PAPEL KRAFT	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2707	, descricao: "	BARRA CHOC AO LEITE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2713	, descricao: "	AGRIAO VERDE HIGIENIZADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2307	, descricao: "	CLORO SANITIZANTE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	182	, descricao: "	CAVA CAST LORD BUT	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2148	, descricao: "	PASTEL LEGUMES	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2331	, descricao: "	DESENGORDURANTE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2354	, descricao: "	FARINHA DE TRIGO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2770	, descricao: "	POTE MOUSSE MOLHEIRA 100ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2694	, descricao: "	OUTROS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	212	, descricao: "	LEGUMES REFOGADOS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	5	, descricao: "	COMBO 3	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	193	, descricao: "	CERVEJA POLVO LOCO VAN GRUPPE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2028	, descricao: "	BOBO FRANGO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2122	, descricao: "	ACETO BALSAMICO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	209	, descricao: "	COMBO PROMO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	169	, descricao: "	CAFE EXPRESSO CORTADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	170	, descricao: "	CAFE EXPRESSO CAPPUCCINO - CANCELADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	194	, descricao: "	CERVEJA SAGRADA GABRIEL PUMPINK IPA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2152	, descricao: "	PIZZA INTEGRAL FRANGO BROCOLIS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2193	, descricao: "	AGRIAO ROXO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2199	, descricao: "	AIPIM	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2203	, descricao: "	ALCOOL LIQ	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2219	, descricao: "	AMIDO DE MILHO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2399	, descricao: "	LEITE DESNATADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2426	, descricao: "	MISTURA DE BROCOLIS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2468	, descricao: "	PASSAS DE UVA BRANCA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2660	, descricao: "	MORANGA VERMELHA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2772	, descricao: "	MOLHO DE PIMENTA SACHET	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2714	, descricao: "	SUCO CONCENTRADO LIMAO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2731	, descricao: "	BARRA HARTS MOVE CACAU	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2267	, descricao: "	CATCHUP BOMBONA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2415	, descricao: "	MANTEIGA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2771	, descricao: "	TAMPA POTE MOUSSE MOLHEIRA 100ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2335	, descricao: "	DETERGENTE MAQ LAVA LOUCAS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2086	, descricao: "	ISCAS CARNE AO FUNGHI	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2773	, descricao: "	MASSA FUSILI	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2123	, descricao: "	MOLHO ITALIANO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	174	, descricao: "	PORCAO PROTEIN SHAKE VEGANA         	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	196	, descricao: "	FELSEN HELLES	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2057	, descricao: "	CREME ABOBORA CARNE PANELA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2124	, descricao: "	MOLHO PARMESAO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2128	, descricao: "	MOLHO MOSTARDA E MEL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2150	, descricao: "	PIMENTA PRETA MOIDA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2151	, descricao: "	PIZZA INTEGRAL 4 QUEJOS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2153	, descricao: "	PIZZA INTEGRAL MARGHERITA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2206	, descricao: "	ALFACE FRIZZE ROXA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2208	, descricao: "	ALFACE MIMOSA ROXA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2249	, descricao: "	CABO RODO E VASSOURA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2388	, descricao: "	IOGURTE MORANGO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2427	, descricao: "	MIX COMPLETO HIGIENIZADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2428	, descricao: "	MIX DE FOLHAS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2441	, descricao: "	NATA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2493	, descricao: "	QUEIJO MUSSARELA RALADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2494	, descricao: "	QUEIJO TOFU NATURAL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2546	, descricao: "	TAMPA POTE 500ML PERSONALIZADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2672	, descricao: "	ABACAXI IQF	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2715	, descricao: "	SUCO CONCENTRADO MARACUJA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2332	, descricao: "	DESINFETANTE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2400	, descricao: "	LEITE INTEGRAL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	133	, descricao: "	COMBINADO VEGETARIANO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	213	, descricao: "	MORANGA ASSADA COM ERVAS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2436	, descricao: "	MORANGA CUBO CONGELADA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2712	, descricao: "	AGRIAO ROXO HIGIENIZADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	199	, descricao: "	FELSEN WEIZENBIER	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	179	, descricao: "	VINHO NOVAS CARM MERLOT	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2168	, descricao: "	SAL REFINADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	237	, descricao: "	BUFFET REALIZE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	175	, descricao: "	PORCAO WHEY OPTIMUM NUTRITION	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2716	, descricao: "	SUCO CONCENTRADO PESSEGO COM MACA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2472	, descricao: "	PEPINO SALADA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2125	, descricao: "	COMPRAS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2170	, descricao: "	SANDUICHE ATUM	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2058	, descricao: "	CREME BATATA DOCE ABOBRINHA FRANGO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2171	, descricao: "	SANDUICHE FRANGO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2209	, descricao: "	ALFACE MIMOSA VERDE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2447	, descricao: "	PALITO INTEGRAL LINHACA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2212	, descricao: "	ALHO PORO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2214	, descricao: "	AMEIXA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2211	, descricao: "	ALHO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2239	, descricao: "	BISCOITO INTEGRAL COM QUEIJO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2492	, descricao: "	QUEIJO GORGONZOLA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2591	, descricao: "	QUEIJO MUSSARELA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2635	, descricao: "	QUEIJO FRESCAL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2711	, descricao: "	SOBREPALETA SUINA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	137	, descricao: "	TILAPIA MOLHO THAY	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	125	, descricao: "	ISCAS DE FRANGO AO CURRY	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2327	, descricao: "	CREME CULINARIO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2346	, descricao: "	ESPONJA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2178	, descricao: "	TORTA INTEGRAL BANANA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2664	, descricao: "	MAMAO IQF	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	6	, descricao: "	KOMBUCHA ORIGINAL	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	238	, descricao: "	EVENTO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2	, descricao: "	ACAI - 250ML	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2365	, descricao: "	FIBRA DE ACO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	233	, descricao: "	MINI HALLS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2096	, descricao: "	LASANHA INTEGRAL BERINGELA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	36	, descricao: "	COCO SECO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	241	, descricao: "	EMBALAGEM MOLHO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2115	, descricao: "	MINI QUICHE FRANGO BATATA DOCE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2464	, descricao: "	PAPEL TOALHA INTERFOLHADO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	200	, descricao: "	FELSEN IRISH STOUT	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	224	, descricao: "	ESFIRRA DE QUEIJO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2735	, descricao: "	SOPA DE TOMATES	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2737	, descricao: "	CHILLI COM CARNE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2237	, descricao: "	BERGAMOTA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	37	, descricao: "	UVA PASSA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2616	, descricao: "	ALFARROBA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	119	, descricao: "	QUICHE DE ESPINAFRE COM SALADA 	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2008	, descricao: "	ALFACE CRESPA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2141	, descricao: "	PAO QUEIJO CONGELADO MULTI GRAO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2114	, descricao: "	MINI QUICHE ESPINAFRE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2496	, descricao: "	RABANETE	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2617	, descricao: "	SNACK TRIBOS 50G	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2389	, descricao: "	IOGURTE TAMBO COM FRUTAS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2637	, descricao: "	CANJICA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2330	, descricao: "	CURRY	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	126	, descricao: "	QUICHE BROCOLIS	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2445	, descricao: "	OLEO DE MILHO	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	129	, descricao: "	BATATA DOCE ASSADA	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	43	, descricao: "	COMBO 2	", unidadeMedida:1},
    { assinanteId:1, produtoId: 	2774	, descricao: "	CARAMELLI ESPINAFRE	", unidadeMedida:1}
  ]);
};

exports.down = async knex => {
	await knex("produto").del();
	await knex("unidade").del();
	return await knex("assinante")
		.del()
		.where("id", 1);
};
